# Generated by Django 2.2.6 on 2019-11-04 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191104_0959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
