"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'mi9f+b3cb#k58-=4m4nv5e#sp(-0+!ie)pnvzrnm%l@(x3slwh'




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'ckeditor',
    'ckeditor_uploader',
    'read_account',
    'comment',
    'likes',
    'user',
    'notifications',
    'my_notifications',
    'captcha',
    # 'social_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 自己写的
                'user.context_processors.login_modal_form',
                # 第三方登陆
                # 'social_django.context_processors.backends',
                # 'social_django.context_processors.login_redirect',
            ],
            # 'libraries':{
            #             'urls_tags':  'user.templatetags.urls_tags',

            # }
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'



# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'static_collected')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# media
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 配置ckeditor
CKEDITOR_UPLOAD_PATH = 'upload/'

CKEDITOR_CONFIGS = {
    'default': {},
    'comment_ckeditor': {
        'toobar': 'custom',
        'toobar_custom': [
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript'],
            ['TextColor', 'BGColor', 'RemoveFormat'],
            ['NumberedList', 'BulletedList'],
            ['Link', 'Unlink'],
            ['Smiley', 'SpecialChar', 'Blockquote'],
        ],
        'width': 'auto',
        'height': '180',
        'tabSpaces': 4,
        'removePlugins': 'elementspath',
        'resize_enabled': False,
    }
}

# 自定义参数
EACH_PAGE_BLOGS_NUMBER = 7

# 缓存设置
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
    }
}


# django-notifications-hq设置，是否使用json数据字段
DJANGO_NOTIFICATIONS_CONFIG = { 
    'USE_JSONFIELD': True,
}




# # 自定义用户验证
# AUTHENTICATION_BACKENDS = (

#     # 'social_core.backends.weibo.WeiboOAuth2',    # 微博
#     'social_core.backends.qq.QQOAuth2',   # qq
#     # 'social_core.backends.weixin.WeixinOAuth2',   # 微信

#     'django.contrib.auth.backends.ModelBackend',    # django默认的必须添加

# )

# SOCIAL_AUTH_WEIBO_KEY = 'foobar'
# SOCIAL_AUTH_WEIBO_SECRET = 'bazqux'

# SOCIAL_AUTH_QQ_KEY = '101831535'
# SOCIAL_AUTH_QQ_SECRET = 'b1355a9e964433f740cb4d37a4790b68'

# # SOCIAL_AUTH_WEIXIN_KEY = 'foobar'
# # SOCIAL_AUTH_WEIXIN_SECRET = 'bazqux'


# SOCIAL_AUTH_LOGIN_REDIRECT_URL = 'http://pengpeng666.top/user/login_by_qq' 



QQ_APP_ID = '101831535'
QQ_APP_KEY = 'b1355a9e964433f740cb4d37a4790b68'
QQ_REDIRECT_URL = 'http://pengpeng666.top/user/login_by_qq'
QQ_STATE = 'pengpeng666'
